package utils

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// run with go test -v ./...

func TestCalculateLevenshteinDist(t *testing.T) {
	ratio := CalculateLevenshteinDist("ACGTTGATACGTCGGTAGAGGCGATTAGAGTGACGATCGGAGTGAGCGTACGTAAAGATGTGCCACCACTGGAATGCGCTTACAAACAGTGGGGATTTGTGTCTGCATCTCCTTCTCCGTCGGTTGGTCGGTTGGGCGCCTGGAGCACATAGATTGTTTTAATTGGTCGATTGACTAAACTAATCTATTACCGCCGTCGTCCTGGTTCTGTTGTGTTGGATAATGTTC", "CACATAGATTG")
	t.Logf("Ratio: %f", ratio)
}

func TestSimiliarityMatch(t *testing.T) {
	verdict, similarity := SimiliarityMatch("ACGTTGATACGTCGGTAGAGGCGATTAGAGTGACGATCGGAGTGAGCGTACGTAAAGATGTGCCACCACTGGAATGCGCTTACAAACAGTGGGGATTTGTGTCTCACCTCGATTGTCCGTCGGTTGGTCGGTTGGGCGCCTGGAGCACATAGATTGTTTTAATTGGTCGATTGACTAAACTAATCTATTACCGCCGTCGTCCTGGTTCTGTTGTGTTGGATAATGTTC", "CACATAGATTG")
	t.Logf("Verdict: %t", verdict)
	t.Logf("Ratio: %f", similarity)
}

func TestBMMatch(t *testing.T) {
	verdict := BMMatch("ACGTTGATACGTCGGTAGAGGCGATTAGAGTGACGATCGGAGTGAGCGTACGTAAAGATGTGCCACCACTGGAATGCGCTTACAAACAGTGGGGATTTGTGTCTGCATCTCCTTCTCCGTCGGTTGGTCGGTTGGGCGCCTGGAGCACATAGATTGTTTTAATTGGTCGATTGACTAAACTAATCTATTACCGCCGTCGTCCTGGTTCTGTTGTGTTGGATAATGTTC", "CACATAGATTG")
	t.Logf("Verdict: %t", verdict)
}

func TestKMPMatch(t *testing.T) {
	verdict := KMPMatch("ACGTTGATACGTCGGTAGAGGCGATTAGAGTGACGATCGGAGTGAGCGTACGTAAAGATGTGCCACCACTGGAATGCGCTTACAAACAGTGGGGATTTGTGTCTGCATCTCCTTCTCCGTCGGTTGGTCGGTTGGGCGCCTGGAGCACATAGATTGTTTTAATTGGTCGATTGACTAAACTAATCTATTACCGCCGTCGTCCTGGTTCTGTTGTGTTGGATAATGTTC", "CACATAGATTG")
	t.Logf("Verdict: %t", verdict)
}

func TestIsValidDNA(t *testing.T) {
	tests := []struct {
		name string
		dna  string
		want bool
	}{
		{"empty string", "", false},
		{"only 1 letter", "A", true},
		{"random", "ACTGTGGATC", true},
		{"incorrect 1 char", "ACTGTG GATC", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := IsValidDNA(tt.dna)
			assert.Equal(t, tt.want, got)
		})
	}
}
